name: jitsi_meet
description: Jitsi Meet Plugin - A plugin for integrating open source Jitsi Meet API in flutter. Jitsi Meet is secure, fully featured and allows completely free video conferencing made with https://jitsi.org, a collection of open source projects
version: 3.0.0
homepage: https://github.com/gunschu/jitsi_meet

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gunschu.jitsi_meet
        pluginClass: JitsiMeetPlugin
      ios:
        pluginClass: JitsiMeetPlugin
