name: jitsi_meet_web_plugin
description: Jitsi Meet Web Plugin
version: 1.0.0
homepage: https://github.com/gunschu/jitsi_meet

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0"
  
dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.2
  meta: ^1.1.7
  flutter_web_plugins:
    sdk: flutter
  jitsi_meet_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      web:
        pluginClass: JitsiMeetPlugin
        fileName: jitsi_meet_web.dart
